language: node_js
node_js:		
  - "6"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=:99.0
  - export CHROME_BIN=chromium-browser
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
branches:
  only: master
script:
  - npm test
  - npm run codecov